# Generated by Django 4.2.7 on 2023-12-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BladeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blade_condition', models.CharField(max_length=255)),
                ('blade_length', models.CharField(max_length=255)),
                ('blade_width', models.CharField(max_length=255)),
                ('blade_od_center', models.CharField(max_length=255)),
                ('actual_od_fn', models.CharField(blank=True, max_length=255)),
                ('actual_od_center', models.CharField(blank=True, max_length=255)),
                ('actual_od_tn', models.CharField(blank=True, max_length=255)),
                ('dressing_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BodyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_condition', models.CharField(max_length=255)),
                ('bore_condition', models.CharField(max_length=255)),
                ('bore_debris_free', models.CharField(max_length=255)),
                ('shoulder_to_shoulder', models.CharField(max_length=255)),
                ('shdr_shdr_length', models.CharField(blank=True, max_length=255)),
                ('float_type', models.CharField(blank=True, max_length=255)),
                ('i_d', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DimensionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('thread_type', models.CharField(max_length=255)),
                ('outside_diameter', models.CharField(max_length=255)),
                ('bevel_diameter', models.CharField(max_length=255)),
                ('counter_bore_length', models.CharField(blank=True, max_length=255)),
                ('cold_work_stamp', models.CharField(blank=True, max_length=255)),
                ('float_bore_back_length', models.CharField(blank=True, max_length=255)),
                ('float_bore_back_diameter', models.CharField(blank=True, max_length=255)),
                ('tong_space', models.CharField(max_length=255)),
                ('fishing_neck', models.CharField(max_length=255)),
                ('internal_diameter', models.CharField(blank=True, max_length=255)),
                ('pin_length', models.CharField(blank=True, max_length=255)),
                ('srg_width', models.CharField(blank=True, max_length=255)),
                ('srg_diameter', models.CharField(blank=True, max_length=255)),
                ('bsr', models.CharField(blank=True, max_length=255)),
                ('box_depth', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=500)),
                ('client_address', models.TextField()),
                ('client_city', models.CharField(max_length=255)),
                ('client_country', models.CharField(max_length=200)),
                ('examination_location', models.TextField()),
                ('contract', models.CharField(blank=True, default='-', max_length=200)),
                ('work_order', models.CharField(max_length=255)),
                ('purchase_order', models.CharField(blank=True, default='-', max_length=255)),
                ('client_job_reference', models.CharField(max_length=255)),
                ('rig', models.CharField(blank=True, default='-', max_length=255)),
                ('report_number', models.CharField(max_length=255)),
                ('revision', models.CharField(max_length=255)),
                ('examination_date', models.CharField(max_length=255)),
                ('next_examination_date', models.DateField(blank=True, null=True)),
                ('examination_area', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=255)),
                ('standards', models.CharField(max_length=255)),
                ('local_procedure_number', models.CharField(max_length=255)),
                ('drawing_number', models.CharField(blank=True, max_length=255)),
                ('test_restrictions', models.CharField(max_length=255)),
                ('surface_condition', models.CharField(max_length=255)),
                ('visual', models.TextField()),
                ('report_type_data', models.JSONField()),
                ('report_status', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('images', models.ImageField(upload_to='reports/')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_details', to='report.statushandler')),
                ('asset_details', models.ManyToManyField(related_name='asset_details', to='report.assetdetail')),
                ('blade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.bladedetail')),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.bodydetail')),
                ('consumables', models.ManyToManyField(related_name='consumables', to='report.consumables')),
                ('dimension_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_one', to='report.dimensiondetail')),
                ('dimension_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_two', to='report.dimensiondetail')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_details', to='report.statushandler')),
                ('keys', models.ManyToManyField(related_name='report_keys', to='report.reportkeys')),
                ('quality_controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_details', to='report.statushandler')),
            ],
        ),
    ]
