# Generated by Django 4.2.7 on 2023-12-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodydetail',
            name='shdr_shdr_length',
        ),
    ]
