# Generated by Django 4.2.7 on 2023-12-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_bodydetail_shdr_shdr_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dimension_one',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='dimension_two',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='DimensionDetail',
        ),
    ]
