# Generated by Django 4.2.7 on 2023-12-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_dimension_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dimension_one_name',
            field=models.CharField(default='Box', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='dimension_two_name',
            field=models.CharField(default='Pin', max_length=10),
            preserve_default=False,
        ),
    ]
