# Generated by Django 4.2.7 on 2023-12-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_dimension_one_name_report_dimension_two_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='NDT', max_length=50),
            preserve_default=False,
        ),
    ]
