# Generated by Django 4.2.7 on 2023-12-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='revision',
        ),
    ]
