# Generated by Django 4.2.7 on 2023-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_report_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='acceptor',
        ),
    ]
