# Generated by Django 4.2.7 on 2023-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_remove_report_acceptor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.RemoveField(
            model_name='report',
            name='asset_details',
        ),
        migrations.AlterField(
            model_name='report',
            name='blade',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='report',
            name='consumables',
        ),
        migrations.AlterField(
            model_name='report',
            name='issuer',
            field=models.JSONField(),
        ),
        migrations.RemoveField(
            model_name='report',
            name='keys',
        ),
        migrations.AlterField(
            model_name='report',
            name='quality_controller',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='AssetDetail',
        ),
        migrations.DeleteModel(
            name='BladeDetail',
        ),
        migrations.DeleteModel(
            name='BodyDetail',
        ),
        migrations.DeleteModel(
            name='Consumables',
        ),
        migrations.DeleteModel(
            name='ReportKeys',
        ),
        migrations.DeleteModel(
            name='StatusHandler',
        ),
        migrations.AddField(
            model_name='report',
            name='asset_details',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='consumables',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='keys',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
