# Generated by Django 4.2.7 on 2023-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_delete_personnel_remove_report_asset_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='images',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
