# Generated by Django 4.2.7 on 2023-12-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_report_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='reports/')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='images',
        ),
        migrations.AddField(
            model_name='report',
            name='images',
            field=models.ManyToManyField(related_name='Report_files', to='report.filemodel'),
        ),
    ]
