# Generated by Django 4.2.7 on 2023-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_filemodel_remove_report_images_report_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='equipments',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
