# Generated by Django 4.2.7 on 2024-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_report_acceptance_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='inspector_signature',
            field=models.ImageField(null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewer_signature',
            field=models.ImageField(null=True, upload_to='reports/'),
        ),
    ]
