# Generated by Django 4.2.7 on 2024-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_report_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='asset_model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
