# Generated by Django 4.2.7 on 2024-01-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receiver', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('receiver_address', models.CharField(max_length=500)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('invoice_data', models.JSONField()),
                ('subtotal', models.FloatField(default=0.0)),
                ('nhl', models.FloatField(default=0.0)),
                ('getfl', models.FloatField(default=0.0)),
                ('covid', models.FloatField(default=0.0)),
                ('total_before_tax', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
