# Generated by Django 4.2.7 on 2023-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_by', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=500)),
                ('invoice_date', models.DateField()),
                ('requirements', models.TextField()),
                ('scope', models.JSONField()),
                ('costs', models.JSONField()),
                ('responsibilities', models.JSONField()),
                ('terms', models.JSONField()),
            ],
        ),
    ]
