# Generated by Django 4.2.7 on 2023-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(default='None yet', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote_number',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
