# Generated by Django 4.2.7 on 2023-12-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_invoice_name_invoice_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default='NDT', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='resources',
            field=models.JSONField(default=[1, 2, 3]),
            preserve_default=False,
        ),
    ]
