# Generated by Django 4.2.7 on 2023-12-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_invoice_type_invoice_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_words',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='mobile_phone_one',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='mobile_phone_two',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
