# Generated by Django 4.2.7 on 2023-12-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_last_words_invoice_mobile_phone_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='signature',
            field=models.ImageField(null=True, upload_to='signatures'),
        ),
    ]
