# Generated by Django 4.2.7 on 2023-12-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='presenter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='presenter_role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
